In [ ]:
import pandas as pd
import numpy as np

# Number of hospitals
n = 300

# Fix random seed
np.random.seed(42)

# Generate hospital data
revenue = np.random.randint(50, 151, n)
debt_ratio = np.round(np.random.uniform(0.1, 0.95, n), 2)
readmission_rate = np.random.randint(5, 31, n)
patient_satisfaction = np.random.randint(50, 96, n)

# Generate balanced risk labels
risk = []

for d, r, p in zip(debt_ratio, readmission_rate, patient_satisfaction):

    score = 0

    if d > 0.70:
        score += 1

    if r > 22:
        score += 1

    if p < 60:
        score += 1

    if score >= 2:
        risk.append("High")

    elif score == 1:
        risk.append("Moderate")

    else:
        risk.append("Safe")

# Create DataFrame
df = pd.DataFrame({
    "Revenue": revenue,
    "DebtRatio": debt_ratio,
    "ReadmissionRate": readmission_rate,
    "PatientSatisfaction": patient_satisfaction,
    "Risk": risk
})

# Save dataset
df.to_csv("hospital.csv", index=False)

print("Dataset Created Successfully!")
print("\nFirst 5 Rows:\n")
print(df.head())

print("\nRisk Distribution:\n")
print(df["Risk"].value_counts())

Dataset Created Successfully!

First 5 Rows:

   Revenue  DebtRatio  ReadmissionRate  PatientSatisfaction      Risk
0      101       0.85               30                   51      High
1      142       0.26                8                   69      Safe
2       64       0.34               30                   77  Moderate
3      121       0.70               12                   60      Safe
4      110       0.82               30                   53      High

Risk Distribution:

Risk
Moderate    137
Safe        105
High         58
Name: count, dtype: int64

In [ ]:
from google.colab import files
files.download("hospital.csv")

In [ ]:
df.head()

   Revenue  DebtRatio  ReadmissionRate  PatientSatisfaction      Risk
0      101       0.85               30                   51      High
1      142       0.26                8                   69      Safe
2       64       0.34               30                   77  Moderate
3      121       0.70               12                   60      Safe
4      110       0.82               30                   53      High

In [ ]:
df["Risk"].value_counts()

Risk
Moderate    137
Safe        105
High         58
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Features
X = df[
    [
        "Revenue",
        "DebtRatio",
        "ReadmissionRate",
        "PatientSatisfaction"
    ]
]

# Target
y = df["Risk"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# Save Model
joblib.dump(model, "hospital_model.pkl")

print("\nModel saved as hospital_model.pkl")

Accuracy: 0.9833333333333333

Classification Report:

              precision    recall  f1-score   support

        High       1.00      0.94      0.97        18
    Moderate       0.96      1.00      0.98        23
        Safe       1.00      1.00      1.00        19

    accuracy                           0.98        60
   macro avg       0.99      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60


Model saved as hospital_model.pkl

In [ ]:
from google.colab import files
files.download("hospital_model.pkl")

In [ ]:
import pandas as pd

df = pd.read_csv("hospital.csv")
print(df.columns)

Index(['Revenue', 'DebtRatio', 'ReadmissionRate', 'PatientSatisfaction',
       'Risk'],
      dtype='object')

In [ ]:
x = df.drop('Risk',axis=1)

In [ ]:
import pandas as pd

df = pd.read_csv("hospital.csv")

print(df["Risk"].unique())

['High' 'Safe' 'Moderate']

In [ ]:
import joblib

model = joblib.load("hospital_model.pkl")

print(model.feature_names_in_)

['Revenue' 'DebtRatio' 'ReadmissionRate' 'PatientSatisfaction']

In [ ]:
print(df["Risk"].unique())

['High' 'Safe' 'Moderate']

In [ ]:
print(model.feature_names_in_)

['Revenue' 'DebtRatio' 'ReadmissionRate' 'PatientSatisfaction']