In [ ]:
!unzip "archive (7).zip"

unzip:  cannot find or open archive (7).zip, archive (7).zip.zip or archive (7).zip.ZIP.

In [ ]:
!ls

insurance.csv  insurance_model.pkl  sample_data

In [ ]:
import pandas as pd

df = pd.read_csv("insurance.csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
def create_risk(charges):

    if charges < 10000:
        return "Low"

    elif charges < 30000:
        return "Medium"

    else:
        return "High"


df["Risk"] = df["charges"].apply(create_risk)

print(df["Risk"].value_counts())

Risk
Low       712
Medium    464
High      162
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sex"] = le.fit_transform(df["sex"])

df["smoker"] = le.fit_transform(df["smoker"])

df["region"] = le.fit_transform(df["region"])

In [ ]:
X = df[
    [
        "age",
        "sex",
        "bmi",
        "children",
        "smoker",
        "region"
    ]
]

y = df["Risk"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score

train_pred = model.predict(X_train)

train_accuracy = accuracy_score(
    y_train,
    train_pred
)

print("Training Accuracy:", train_accuracy)

Training Accuracy: 0.9981308411214953

In [ ]:
test_pred = model.predict(X_test)

test_accuracy = accuracy_score(
    y_test,
    test_pred
)

print("Testing Accuracy:", test_accuracy)

Testing Accuracy: 0.9402985074626866

In [ ]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        test_pred
    )
)

              precision    recall  f1-score   support

        High       1.00      0.91      0.95        32
         Low       0.93      0.98      0.95       143
      Medium       0.94      0.89      0.92        93

    accuracy                           0.94       268
   macro avg       0.96      0.93      0.94       268
weighted avg       0.94      0.94      0.94       268

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(
    y_test,
    test_pred
)

print(cm)

[[ 29   1   2]
 [  0 140   3]
 [  0  10  83]]

In [ ]:
import joblib

joblib.dump(
    model,
    "insurance_model.pkl"
)

print("Model Saved Successfully!")

Model Saved Successfully!

In [ ]:
from google.colab import files

files.download(
    "insurance_model.pkl"
)

In [ ]:
sample = [[
    55,   # age
    1,    # sex
    35.5, # bmi
    2,    # children
    1,    # smoker
    2     # region
]]

prediction = model.predict(sample)

print(
    "Predicted Risk:",
    prediction[0]
)

Predicted Risk: High

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
import joblib

model = joblib.load("insurance_model.pkl")

print(model.feature_names_in_)

['age' 'sex' 'bmi' 'children' 'smoker' 'region']

In [ ]:
import pandas as pd

df = pd.read_csv("/content/insurance.csv")

print(df.head())
print(df.columns)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [ ]:
import pandas as pd

df = pd.read_csv("insurance.csv")

print(df.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
print(df["sex"].unique())
print(df["smoker"].unique())
print(df["region"].unique())

['female' 'male']
['yes' 'no']
['southwest' 'southeast' 'northwest' 'northeast']