In [ ]:
import pandas as pd
import numpy as np

# Number of pharma companies
n = 300

np.random.seed(42)

# Features
rd_spend = np.random.randint(50, 301, n)          # million $
revenue_growth = np.random.randint(-10, 26, n)    # %
trial_success = np.round(np.random.uniform(0.1, 1.0, n), 2)

recommendation = []

for rd, rev, trial in zip(rd_spend, revenue_growth, trial_success):

    score = 0

    if trial > 0.75:
        score += 1

    if rev > 10:
        score += 1

    if rd > 200:
        score += 1

    if score >= 2:
        recommendation.append("Buy")

    elif score == 1:
        recommendation.append("Hold")

    else:
        recommendation.append("Sell")

# Create DataFrame
df_pharma = pd.DataFrame({
    "RDSpend": rd_spend,
    "RevenueGrowth": revenue_growth,
    "TrialSuccess": trial_success,
    "Recommendation": recommendation
})

# Save dataset
df_pharma.to_csv("pharma.csv", index=False)

print("Pharma Dataset Created Successfully!")
print(df_pharma.head())

print("\nDistribution:")
print(df_pharma["Recommendation"].value_counts())

Pharma Dataset Created Successfully!
   RDSpend  RevenueGrowth  TrialSuccess Recommendation
0      152             21          0.15           Hold
1      229             -7          0.76            Buy
2      142              0          0.59           Sell
3       64              6          0.74           Sell
4      156             13          0.97            Buy

Distribution:
Recommendation
Hold    133
Buy     104
Sell     63
Name: count, dtype: int64

In [ ]:
df_pharma["Recommendation"].value_counts()

Recommendation
Hold    133
Buy     104
Sell     63
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Features
X = df_pharma[
    [
        "RDSpend",
        "RevenueGrowth",
        "TrialSuccess"
    ]
]

# Target
y = df_pharma["Recommendation"]

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Results
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# Save Model
joblib.dump(model, "pharma_model.pkl")

print("\nModel saved as pharma_model.pkl")

Accuracy: 0.9666666666666667

Classification Report:

              precision    recall  f1-score   support

         Buy       1.00      0.89      0.94        19
        Hold       0.93      1.00      0.97        28
        Sell       1.00      1.00      1.00        13

    accuracy                           0.97        60
   macro avg       0.98      0.96      0.97        60
weighted avg       0.97      0.97      0.97        60


Model saved as pharma_model.pkl

In [ ]:
from google.colab import files
files.download("pharma.csv")

In [ ]:
from google.colab import files
files.download("pharma_model.pkl")

In [ ]:
sample = [[250, 18, 0.90]]

prediction = model.predict(sample)

print(prediction)

['Buy']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
import pandas as pd

df = pd.read_csv("pharma.csv")

print(df["Recommendation"].unique())

['Hold' 'Buy' 'Sell']

In [ ]:
import pandas as pd

df = pd.read_csv("pharma.csv")

print(df["Recommendation"].unique())

['Hold' 'Buy' 'Sell']

In [ ]:
import joblib

model = joblib.load("pharma_model.pkl")

print(model.feature_names_in_)

['RDSpend' 'RevenueGrowth' 'TrialSuccess']

In [ ]:
import joblib

model = joblib.load("pharma_model.pkl")

print(model.predict([[100000, -20, 10]]))
print(model.predict([[500000, 10, 50]]))
print(model.predict([[1000000, 30, 90]]))

['Buy']
['Buy']
['Buy']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [ ]:
df["Recommendation"].value_counts()

Recommendation
Hold    133
Buy     104
Sell     63
Name: count, dtype: int64

In [ ]:
import joblib

model = joblib.load("pharma_model.pkl")

print(model.predict([[100000, -20, 10]]))
print(model.predict([[500000, 10, 50]]))
print(model.predict([[1000000, 30, 90]]))

['Buy']
['Buy']
['Buy']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(